[package]
name = "fcsigner"
version = "0.1.0"
authors = ["Zondax <info@zondax.ch>"]
edition = "2018"

[dependencies]
num = "0.2.1"
anyhow = "1.0"
    
# FIXME: Check API compatibility
parity-secp256k1 = "0.7.0"

# FIXME: confirm compatibility with WASM target
[dependencies.rand]
version = "0.7.3"
