[package]
name = "fcsigner"
version = "0.1.0"
authors = ["Zondax <info@zondax.ch>"]
edition = "2018"

[dependencies]
serde = "1.0.102"
serde_json = "1.0.41"
serde_cbor = "0.10.2"
num = "0.2.1"

parity-secp256k1 = "0.7.0"

[dependencies.rand]
version = "0.7.3"
