# filecoin-service - Example configuration file# https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest

[remote_node]
#url = "http://127.0.0.1:1234/rpc/v0"
url = "https://proxy.openworklabs.com/rpc/v0"
jwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.Ow965XBlQKksfRmepJCkBsMqm_jdJ3_8Of1HF6PibRc"

[service]
address = "127.0.0.1:3030"
