# filecoin-service - Example configuration file# https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest

[remote_node]
url = "LOTUS_SECRET_URL"
jwt = "LOTUS_SECRET_JWT"

[service]
address = "127.0.0.1:3030"
