version: 2.0

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: build
          command: |
            rustc --version
            cargo --version
            cargo build
      - run:
          name: build --release
          command: |
            rustc --version
            cargo --version
            cargo build --release

  build_wasm:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo install wasm-pack --version 0.8.1
      - run:
          name: versions
          command: |
            rustc --version
            cargo --version
            wasm-pack --version
      - run:
          name: build
          command: |
            wasm-pack build fcwebsigner/

  checks:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustup component add clippy
      - run: cargo install cargo-audit
      - run:
          name: rustfmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: clippy
          command: |
            cargo clippy --version
            cargo clippy --all-features
      - run:
          name: audit
          command: |
            cargo audit --version
            cargo audit

  tests_rust:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: test --all-features
          command: |
            rustc --version
            cargo --version
            cargo test --lib --all-features

  test_wasm:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: install node + yarn + n
          command: |
            sudo apt install nodejs
            sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update && sudo apt install yarn
            sudo yarn global add n
            sudo n latest -q
      - run:
          name: install node + yarn + n
          command: |
            make deps
            make build_wasm
            make link_wasm
            make test_wasm
#      - run:
#          name: versions
#          command: |
#            rustc --version
#            cargo --version
#            wasm-pack --version
#      - run:
#          name: build
#          command: |
#            wasm-pack build fcwebsigner/

workflows:
  version: 2
  build_all:
    jobs:
      - checks
      - build:
          requires:
            - checks
      - tests_rust:
          requires:
            - build

      - build_wasm:
          requires:
            - checks

