name: "Publish js packages"

on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+(\\.[0-9]+)*"

jobs:
  publish_npm_package:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Restore/Save sscache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/sccache
          key: ${{ runner.os }}-${{ github.run_id }}-${{ needs.configure.outputs.datetime }}
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install yarn
        run: npm install -g yarn
      - run: make install_wasmpack SILENT=true
      - run: make build_npm
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Update tag
        run: |
          cd signer-npm/pkg
          echo Publishing as ${{ steps.get_version.outputs.version }}
          npm --allow-same-version --no-git-tag-version version ${{ steps.get_version.outputs.version }}
      - name: Publish package
        run: |
          cd signer-npm/pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
